import type { Metadata } from "next";
import "../../globals.css";
import Header from "../../components/layout/Header";
import { FunctionalitesProvider } from "@/context/useUrl";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
       <>
        <Header />
        <FunctionalitesProvider>
            <main className="flex-grow max-w-screen-2xl mx-auto space-y-6 relative text-center">
                {children}
            </main>
        </FunctionalitesProvider>
        <footer className="w-full flex-col p-4 bg-black text-white/60">
            <section className="flex flex-wrap justify-start gap-8 w-full mb-4">
                  <div className="flex flex-col items-start justify-center gap-4 w-fit">
                      <p className="text-lg font-bold text-white">Links rápidos</p>
                      <ul className="space-y-2 mx-2">
                          <li className="text-start text-lg w-fit cursor-pointer hover:text-mainBgButton transition-all duration-300 ease-in-out">
                              <Link href="/#">Github</Link>
                          </li>
                          <li className="text-start text-lg w-fit cursor-pointer hover:text-mainBgButton transition-all duration-300 ease-in-out">
                              <Link href="/#">Contact Us</Link>
                          </li>
                          <li className="text-start text-lg w-fit cursor-pointer hover:text-mainBgButton transition-all duration-300 ease-in-out">
                              <Link href="/#">Home</Link>
                          </li>
                      </ul>
                  </div>
                  <div className="flex flex-col items-start justify-center gap-4 w-fit text-secondary">
                      <p className="text-lg font-bold text-white">Links rápidos</p>
                      <ul className="space-y-2">
                          <li className="text-start text-lg w-fit cursor-pointer hover:text-mainBgButton transition-all duration-300 ease-in-out">
                              <Link href="/#">Github</Link>
                          </li>
                          <li className="text-start text-lg w-fit cursor-pointer hover:text-mainBgButton transition-all duration-300 ease-in-out">
                              <Link href="/#">Contact Us</Link>
                          </li>
                          <li className="text-start text-lg w-fit cursor-pointer hover:text-mainBgButton transition-all duration-300 ease-in-out">
                              <Link href="/#">Home</Link>
                          </li>
                      </ul>
                  </div>
                  <div className="flex flex-col items-start justify-center gap-4 w-fit">
                      <p className="text-lg font-bold text-white">Links rápidos</p>
                      <ul className="space-y-2">
                          <li className="text-start text-lg w-fit cursor-pointer hover:text-mainBgButton transition-all duration-300 ease-in-out">
                              <Link href="/#">Github</Link>
                          </li>
                          <li className="text-start text-lg w-fit cursor-pointer hover:text-mainBgButton transition-all duration-300 ease-in-out">
                              <Link href="/#">Contact Us</Link>
                          </li>
                          <li className="text-start text-lg w-fit cursor-pointer hover:text-mainBgButton transition-all duration-300 ease-in-out">
                              <Link href="/#">Home</Link>
                          </li>
                      </ul>
                  </div>
              </section>
              <section className="flex flex-wrap border-t p-4 border-gray-800/80 items-center gap-4 justify-center sm:justify-between w-full">
                  <p className="text-base tracking-widest">
                      TEACH<span className="text-mainBgButton">L</span>YZE
                  </p>
                  <div className="flex text-sm items-center gap-4 sm:ml-auto">
                      <p className="">© 2025 TCC All rights reserved</p>
                      <Link href={""} className="hover:text-mainBgButton transition-all duration-300 ease-in-out">
                          Terms
                      </Link>
                      <Link href={""} className="hover:text-mainBgButton transition-all duration-300 ease-in-out">
                          Privacy
                      </Link>
                      <Link href={""} className="hover:text-mainBgButton transition-all duration-300 ease-in-out">
                          Docs
                      </Link>
                  </div>
              </section>
          </footer>
        </>
  );
}
