import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/layout/Header";
import Template from "./template";
import UrlProvider from "@/context/useUrl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className="flex flex-col bg-white overflow-x-hidden">
        <UrlProvider>
          <Header />
          <main className="flex-grow space-y-6 relative text-center">
            <Template>{children}</Template>
          </main>
        </UrlProvider>
      </body>
    </html>
  );
}
