import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/layout/Header";
import { FunctionalitesProvider } from "@/context/useUrl";
import Template from "./template";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className="flex flex-col bg-slate-200 overflow-x-hidden">
        <FunctionalitesProvider>
          <Header />
          <main className="flex-grow max-w-screen-2xl mx-auto space-y-6 relative text-center">
            <Template>{children}</Template>
          </main>
        </FunctionalitesProvider>
      </body>
    </html>
  );
}
