import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/layout/Header";
import Main from "./components/layout/Main";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className="flex flex-col bg-white overflow-x-hidden">
        <Header />
        <div className="flex">
          <Main children={children} />
        </div>
      </body>
    </html>
  );
}
